version: '3'

services:
  
  app:
    build: .
    container_name: clean_architecture_app
    volumes:
      - .:/usr/src/app
      - node_modules:/usr/src/app/node_modules/

volumes:
  node_modules:
